# -*- coding: utf-8 -*-
"""task01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OVR6o_1XMI1spgxfZmv-1RVIMg7kkUEc

Name: Victoria Franceschini Pizza
rm: 550609
2ESPG
20/03
"""

import pandas as pd

# Creating a function to count the characters in the "Director" field
def contar_caracteres(titles):
    return len(titles)

# # Reading the CSV file and loading the data into a DataFrame
df_filmes = pd.read_csv('/netflix_titles.csv')

# Sorting the data by the "data_added" column
df_ordenado_por_data = df_filmes.sort_values(by='date_added')

# Sorting the data by the "released_year" column
df_ordenado_por_ano = df_filmes.sort_values(by='release_year')

# Counting the number of films per year
contagem_por_ano = df_filmes['release_year'].value_counts()
print(contagem_por_ano)

# Getting the Unique Years from Movies
anos_unicos = df_filmes['release_year'].unique()
print(anos_unicos)

# Checking the first few rows of the DataFrame to ensure the data was loaded correctly
print(df_filmes.head())

# Generating a list of film countries
lista_paises = df_filmes['country'].value_counts()

# Displaying the list of countries
print(lista_paises)

# Occurrence count for column 'country'
contagem_paises = df_filmes['country'].value_counts()

# Count of occurrences for the 'rating' column
contagem_classificacao = df_filmes['rating'].value_counts()

# Viewing Hit Counts
print("Contagem de países:")
print(contagem_paises)

# age rating count
print("\nContagem de classificação de idade:")
print(contagem_classificacao)

# Creating new columns with the fourth and tenth characters of the "Director" field
df_filmes['quarto_caractere'] = df_filmes['title'].apply(lambda x: x[3] if len(x) > 3 else None)
df_filmes['decimo_terceiro_caractere'] = df_filmes['title'].apply(lambda x: x[12] if len(x) > 12 else None)

# Displaying the first rows of the DataFrame to check for new columns
print(df_filmes.head())

# Displaying the first rows of the DataFrame to check the new column
print(df_filmes.head())

# Displaying the first rows of ordered DataFrames
print("Ordenado por data_added:")
print(df_ordenado_por_data.head())

print("\nOrdenado por released_year:")
print(df_ordenado_por_ano.head())

# print the DataFrame information to the output cell below
df_filmes.info()

#existing columns
df_filmes.columns

# display the first few rows of a DataFrame called df_filmes.
df_filmes.head(10)